#!/bin/sh

attempt=0
radio_path=""
while [ "$attempt" -lt 15 ]; do
    uci -q get wireless.radio0 >/dev/null 2>&1 || wifi config
    radio_path="$(uci -q get wireless.radio0.path)"
    [ -n "$radio_path" ] && break
    attempt=$((attempt + 1))
    sleep 1
done

case "$radio_path" in
    *ffe03000.mmc/mmc_host/mmc0/mmc0:0001/mmc0:0001:1) ;;
    "") exit 1 ;;
    *) exit 0 ;;
esac

uci -q get wireless.default_radio0 >/dev/null 2>&1 \
    || uci set wireless.default_radio0='wifi-iface'

uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='SG'
uci set wireless.radio0.band='5g'
uci set wireless.radio0.channel='149'
uci set wireless.radio0.htmode='VHT80'
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.device='radio0'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.ssid='ImmortalWrt'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.default_radio0.disabled='0'
uci commit wireless
wifi reload

exit 0
